[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install setuptools wheel",
  "pip install -r requirements.txt"
]

[start]
cmd = "python -m app.main"

